<a href="https://colab.research.google.com/github/Aravindhmani/ssh/blob/master/May%2001%20test%20code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

mylist = [1,2,3,4,5,6]

samplearray = np.array(mylist , dtype=int)
print(samplearray)

print(len(samplearray))
print(type(samplearray))
print(samplearray.ndim)
print(samplearray.shape)



[1 2 3 4 5 6]
6
<class 'numpy.ndarray'>
1
(6,)


In [12]:
samplearray1 = samplearray.reshape(3,-1)
print(samplearray1)
samplearray1.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [14]:
samplearray2 = samplearray.reshape(3,-1)
print(samplearray2)

samplearray2.ndim

[[1 2]
 [3 4]
 [5 6]]


2

In [23]:
my_list1 = [1,2,3,4,5,6]
my_list2 = [7,8,9,10,11,12]
my_list3 = [13,14,15,16,17,18]

mul_array = np.array([my_list1,my_list2,my_list3])
print(mul_array)

print(mul_array.ndim)
print(mul_array.shape)

mul_array.reshape()

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
2
(3, 6)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [26]:
arr=range(12)
print(arr)

range(0, 12)


In [36]:
newarr=np.arange(1,13,1)
print(newarr)
newarr.ndim


[ 1  2  3  4  5  6  7  8  9 10 11 12]


1

In [39]:

newarr1 = newarr.reshape(3,4)
print(newarr1)
newarr1.ndim

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2

In [44]:
x=np.array([[1,3],[4,5]],dtype=np.float64)
y=np.array([[6,7],[8,9]],dtype=np.float64)
print(x)
print(y)

print(x+y)
print(np.add(x,y))

[[1. 3.]
 [4. 5.]]
[[6. 7.]
 [8. 9.]]
[[ 7. 10.]
 [12. 14.]]
[[ 7. 10.]
 [12. 14.]]


In [45]:
print(np.subtract(x,y))

[[-5. -4.]
 [-4. -4.]]


In [47]:
print(np.multiply(x,y))
print(x*y)

[[ 6. 21.]
 [32. 45.]]
[[ 6. 21.]
 [32. 45.]]


In [48]:
print(np.dot(x,y))

[[30. 34.]
 [64. 73.]]


In [50]:
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

13.0
[5. 8.]
[4. 9.]
